# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - shortfin - SDXL

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/ci-sdxl.yaml'
      - 'shortfin/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-sdxl.yaml'
      - 'shortfin/**'

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  IREE_REPO_DIR: ${{ github.workspace }}/iree
  LIBSHORTFIN_DIR: ${{ github.workspace }}/shortfin/

jobs:
  build-and-test:
    name: Build and test
    runs-on: mi300-sdxl-kernel

    steps:
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install cmake ninja-build -y

    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        submodules: false

    - name: Checkout IREE repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        repository: iree-org/iree
        path: ${{ env.IREE_REPO_DIR }}
        submodules: false
        ref: candidate-20241029.1062

    - name: Initalize IREE submodules
      working-directory: ${{ env.IREE_REPO_DIR }}
      run : |
        git submodule update --init --depth 1 -- third_party/benchmark
        git submodule update --init --depth 1 -- third_party/cpuinfo/
        git submodule update --init --depth 1 -- third_party/flatcc
        git submodule update --init --depth 1 -- third_party/googletest
        git submodule update --init --depth 1 -- third_party/hip-build-deps/

    - name: Setup Python
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: "3.12"
        cache: "pip"
    - name: Install Python packages
      # TODO: Switch to `pip install -r requirements.txt -e shortfin/`.
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        pip install -r requirements-tests.txt
        pip install -r requirements-iree-compiler.txt
        pip freeze

    - name: Build shortfin (full)
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        mkdir build
        cmake -GNinja \
          -S. \
          -Bbuild \
          -DCMAKE_C_COMPILER=clang-18 \
          -DCMAKE_CXX_COMPILER=clang++-18 \
          -DSHORTFIN_BUNDLE_DEPS=ON \
          -DSHORTFIN_IREE_SOURCE_DIR="${{ env.IREE_REPO_DIR }}" \
          -DSHORTFIN_BUILD_PYTHON_BINDINGS=ON
        cmake --build build --target all
        pip install -v -e build/

    - name: Test shortfin (full)
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        ctest --timeout 30 --output-on-failure --test-dir build
        HIP_VISIBLE_DEVICES=0 pytest tests/apps/sd/e2e_test.py -v -s --system=amdgpu
