# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - shortfin - Python 3.13 Free-threaded

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/ci_linux_x64-libshortfin.yml'
      - 'shortfin/**'

  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci_linux_x64-libshortfin.yml'
      - 'shortfin/**'

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  IREE_REPO_DIR: ${{ github.workspace }}/iree
  LIBSHORTFIN_DIR: ${{ github.workspace }}/shortfin/

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install clang lld cmake ninja-build

    - name: Checkout IREE repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: iree-org/iree
        path: ${{ env.IREE_REPO_DIR }}
        submodules: false
        ref: iree-3.1.0rc20241220

    - name: Initalize IREE submodules
      working-directory: ${{ env.IREE_REPO_DIR }}
      run : |
        git submodule update --init --depth 1 -- third_party/benchmark
        git submodule update --init --depth 1 -- third_party/cpuinfo/
        git submodule update --init --depth 1 -- third_party/flatcc
        git submodule update --init --depth 1 -- third_party/googletest
        git submodule update --init --depth 1 -- third_party/hip-build-deps/

    - name: Setup Python
      uses: deadsnakes/action@e640ac8743173a67cca4d7d77cd837e514bf98e8 # v3.2.0
      with:
        python-version: "3.13-dev"
        nogil : true
    - name: Install Python packages
      run: |
        pip install -r ${{ env.LIBSHORTFIN_DIR }}/requirements-tests-nogil.txt
        pip freeze

    - name: Build shortfin (full)
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        mkdir build
        cmake -GNinja \
          -S. \
          -Bbuild \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_C_COMPILER=clang-18 \
          -DCMAKE_CXX_COMPILER=clang++-18 \
          -DCMAKE_LINKER_TYPE=LLD \
          -DSHORTFIN_BUNDLE_DEPS=ON \
          -DSHORTFIN_IREE_SOURCE_DIR="${{ env.IREE_REPO_DIR }}" \
          -DSHORTFIN_BUILD_PYTHON_BINDINGS=ON
        cmake --build build --target all
        pip install -v -e build/

    - name: Run shortfin Python tests (full)
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        pytest -s --ignore=tests/examples/fastapi_test.py --ignore=tests/apps/sd
      # TODO: Enable further tests and switch to
      # pytest -s
